[package]
authors = ["gyu-don <takumi.kt+git@gmail.com>"]
name = "encoding-io"
version = "0.1.0"

[dependencies]
bufstream = "0.1.3"
encoding_rs = "0.6.11"

[[example]]
name = "sjis-reader"
path = "example/sjis_reader.rs"
